name: CI

on:
  push:
    branches:
      - master
      - feature/*
      - chore/*
      - fix/*
  pull_request:
    branches:
      - master
      - feature/*
      - chore/*
      - fix/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
